name: Deploy Production Environment
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
jobs:
  publish:
    environment: production
    name: Build and make dist tar
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Setup Node.js environment
        uses: actions/setup-node@v5.0.0
      - name: Build target
        run: |
          export VITE_API_BASE_URL=${{ vars.API_BASE_URL }} && \
          npm install -g pnpm && \
          pnpm i && \
          pnpm run build
      - name: Copy to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.PROD_SERVER_HOST }}
          username: ${{ secrets.PROD_SERVER_USERNAME }}
          password: ${{ secrets.PROD_SERVER_PASSWORD }}
          port: 22
          source: "dist/*"
          target: "~/deploy_temp"
          rm: true
          strip_components: 1
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_SERVER_HOST }}
          username: ${{ secrets.PROD_SERVER_USERNAME }}
          password: ${{ secrets.PROD_SERVER_PASSWORD }}
          port: 22
          script: |
            rm -rf ${{ vars.SERVER_DEPLOY_PATH }}/*
            mv ~/deploy_temp/* ${{ vars.SERVER_DEPLOY_PATH }}/
            rm -rf ~/deploy_temp
